"""
tools/diagram_tools.py — Save C4 diagrams (Mermaid) and architecture documentation
to the project repository. Used by the Architect agent.
"""

import os
from langchain_core.tools import tool
from core.logger import log_tool_call, log_tool_result, log_error


DIAGRAM_HEADER = """<!-- Generated by Architect Agent — C4 Model -->
<!-- https://c4model.com/ -->

"""


@tool
def save_c4_diagram(repo_path: str, diagram_type: str, content: str) -> str:
    """
    Save a C4 Mermaid diagram to docs/architecture/<type>.md.
    diagram_type should be one of: context, containers, components.
    """
    log_tool_call("architect", "save_c4_diagram", {
        "repo_path":    repo_path,
        "diagram_type": diagram_type,
        "content_len":  f"{len(content)} chars",
    })
    try:
        docs_path = os.path.join(repo_path, "docs", "architecture")
        os.makedirs(docs_path, exist_ok=True)

        filename = f"{diagram_type.lower()}.md"
        filepath = os.path.join(docs_path, filename)

        title_map = {
            "context":    "C4 Context Diagram",
            "containers": "C4 Containers Diagram",
            "components": "C4 Components Diagram",
        }
        title = title_map.get(diagram_type.lower(), f"C4 {diagram_type.title()} Diagram")

        full_content = (
            DIAGRAM_HEADER
            + f"# {title}\n\n"
            + "```mermaid\n"
            + content.strip()
            + "\n```\n"
        )
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(full_content)

        result = f"✓ Saved {diagram_type} diagram → {filepath}"
        log_tool_result("save_c4_diagram", result)
        return result
    except Exception as e:
        log_error("architect", str(e))
        return f"ERROR: {e}"


@tool
def save_architecture_doc(repo_path: str, content: str) -> str:
    """
    Save the full technical architecture document to docs/DOCUMENTATION.md.
    """
    log_tool_call("architect", "save_architecture_doc", {
        "repo_path":   repo_path,
        "content_len": f"{len(content)} chars",
    })
    try:
        docs_path = os.path.join(repo_path, "docs")
        os.makedirs(docs_path, exist_ok=True)
        filepath = os.path.join(docs_path, "DOCUMENTATION.md")
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        result = f"✓ Architecture doc saved → {filepath}"
        log_tool_result("save_architecture_doc", result)
        return result
    except Exception as e:
        log_error("architect", str(e))
        return f"ERROR: {e}"


@tool
def save_tech_stack_json(repo_path: str, tech_stack: dict) -> str:
    """
    Persist the tech-stack decision as docs/tech_stack.json.
    """
    import json
    log_tool_call("architect", "save_tech_stack_json", {
        "repo_path":  repo_path,
        "tech_stack": str(tech_stack),
    })
    try:
        docs_path = os.path.join(repo_path, "docs")
        os.makedirs(docs_path, exist_ok=True)
        filepath = os.path.join(docs_path, "tech_stack.json")
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(tech_stack, f, indent=2)
        result = f"✓ Tech stack saved → {filepath}"
        log_tool_result("save_tech_stack_json", result)
        return result
    except Exception as e:
        log_error("architect", str(e))
        return f"ERROR: {e}"