from __future__ import annotations

import enum
from datetime import datetime
from typing import List, Optional

from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import relationship

from app.db.base import Base


class StatusEnum(str, enum.Enum):
    """Enumeration of possible task statuses."""

    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"


class PriorityEnum(str, enum.Enum):
    """Enumeration of possible task priorities."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class User(Base):
    """SQLAlchemy model representing an application user.

    Attributes:
        id: Primary key.
        email: Unique e‑mail address.
        hashed_password: Password hash generated by ``hash_password``.
        created_at: Timestamp of record creation.
        tasks: Collection of tasks owned by the user.
    """

    __tablename__ = "user"

    id: int = Column(Integer, primary_key=True, index=True)
    email: str = Column(String, nullable=False, unique=True, index=True)
    hashed_password: str = Column(String, nullable=False)
    created_at: datetime = Column(
        DateTime,
        nullable=False,
        server_default=func.now(),
    )
    # Soft‑delete column is present in the DB schema but not required for core logic.
    deleted_at: Optional[datetime] = Column(DateTime, nullable=True)

    tasks: List[Task] = relationship(
        "Task",
        back_populates="owner",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        """Return a developer‑friendly string representation."""
        return f"<User id={self.id} email={self.email!r}>"


class Task(Base):
    """SQLAlchemy model representing a to‑do task.

    Attributes:
        id: Primary key.
        title: Short title of the task.
        description: Optional detailed description.
        status: Current status of the task.
        priority: Priority level of the task.
        created_at: Timestamp of record creation.
        updated_at: Timestamp of last modification.
        user_id: Foreign key referencing the owning ``User``.
        owner: Relationship back to the ``User`` instance.
    """

    __tablename__ = "task"

    id: int = Column(Integer, primary_key=True, index=True)
    title: str = Column(String, nullable=False)
    description: Optional[str] = Column(Text, nullable=True)
    status: StatusEnum = Column(
        SAEnum(StatusEnum, name="status_enum"),
        nullable=False,
        default=StatusEnum.TODO,
    )
    priority: PriorityEnum = Column(
        SAEnum(PriorityEnum, name="priority_enum"),
        nullable=False,
        default=PriorityEnum.MEDIUM,
    )
    created_at: datetime = Column(
        DateTime,
        nullable=False,
        server_default=func.now(),
    )
    updated_at: datetime = Column(
        DateTime,
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    user_id: int = Column(Integer, ForeignKey("user.id", ondelete="CASCADE"), nullable=False)
    # Soft‑delete column is present in the DB schema but not required for core logic.
    deleted_at: Optional[datetime] = Column(DateTime, nullable=True)

    owner: User = relationship("User", back_populates="tasks", lazy="joined")

    def __repr__(self) -> str:
        """Return a developer‑friendly string representation."""
        return f"<Task id={self.id} title={self.title!r} status={self.status} priority={self.priority}>"

__all__: list[str] = ["User", "Task", "StatusEnum", "PriorityEnum"]